#!/bin/ash

if [ "$1" = "wan" ]; then
    uci set network.wan.device='eth0.2'
    uci del network.cfg020f15.ports
    uci add_list network.cfg020f15.ports='eth0.1'
    uci commit
    /etc/init.d/network restart
elif [ "$1" = "lan" ]; then
    uci set network.wan.device='eth0.1'
    uci del network.cfg020f15.ports
    uci add_list network.cfg020f15.ports='eth0.2'
    uci commit
    /etc/init.d/network restart
else
    echo "Parameter must be wan or lan"
fi
