src-include defaults feeds.conf.default
src-git 3ginfo  https://github.com/4IceG/luci-app-3ginfo-lite.git^bb0b42f66f300a8e50208d91e9a3c29325cdc187
src-git smstool https://github.com/4IceG/luci-app-sms-tool.git^9cbd2b3fd261984de2eaff69c84a98385e0be00b
