src-include defaults feeds.conf.default
src-git 3ginfo     https://github.com/4IceG/luci-app-3ginfo-lite.git^1798aee4ac18511ae3507fdcc10377b2ec6394d9
src-git smstool    https://github.com/4IceG/luci-app-sms-tool-js.git^0c4f2d36c19d16368c41db15f199fb0b87be1a12
src-git atcommands https://github.com/4IceG/luci-app-atcommands.git^5bc400c523c9331b19761d3ef95624e244161eb3
src-git modemband  https://github.com/4IceG/luci-app-modemband.git^d8b8966f74379ea3593c09c0729e4f3f64084619
